export interface Section1Type {
	name: string;
	dpid: string;
	age: string;
	gender: string;
	personalHistory: string;
	occupation: string;
	allergiesToMedication: string;
	covid: string;
	homecareHospitalized: string;
	ventilatorProlongedLifeSupport: string;
	diabeticStatus: string;
	immunoCompromised: string;
	steroidHistory: string;
	postCovidSymptoms: Array<string>;
	sinusitis: string;
	nasalBlockage: string;
	blackishDiscoloration: string;
	facialErythema: string;
	eyeSymptoms: string;
	facialPainNumbness: string;
	toothacheMobileTooth: string;
	palatalUlceration: string;
	halitosis: string;
	skinLesions: string;
	fever: string;
	headache: string;
	alteredSensorium: string;
}
