name: Build Flutter App for IOS and Android
on:
  push:
    paths:
      - 'app/**'
    branches:
      - main

jobs:
  build:
    name: Build and Test Android and IOS App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'dev'
      - name: Install dependencies
        working-directory: app
        run: flutter pub get
      - name: Build for Android
        working-directory: mobile
        run: flutter build apk --split-per-abi
      - name: Build for IOS
        working-directory: mobile
        run: flutter build ios --release --no-codesign
